### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by anuragmundhada** [vumaasha/Atlas#2]
The links seem to have changed, as a result the download script is broken. Any way to download the images directly?

**Comment by vumaasha** [comment]
Could you please share the email that you used to agree on the Dataset agreement before downloading the dataset?

**Comment by anuragmundhada** [comment]
pejorates@blogfortetreinosuplementos.com


> Could you please share the email that you used to agree on the Dataset agreement before downloading the dataset?

pejorates@blogfortetreinosuplementos.com

Thanks!

**Comment by vumaasha** [comment]
You have few options
1. ignore the broken links and download the other images
2.  Rerun the crawlers
3. If you could provide a valid affiliation with valid credentials and signed agreement copy. We could consider sharing the actual dataset with you.

**Comment by anuragmundhada** [comment]
Getting in touch with you offline; closing the issue. Thanks
