### ISSUE TITLE
Broken links and crawler inputs

### ISSUE THREAD

**Issue by Bouncer51** [vumaasha/Atlas#6]
Hello,

The links in JSON file i downloaded "atlas_dataset" are not valid anymore, is there any csv file available as mentioned in "data collection" on which i could run the crawler? 

Actually i would need image link along with product description (which is missing in current dataset)

TIA

**Comment by GirishShanmugam** [comment]
This project is not actively maintained anymore. So we are not monitoring and updating the JSON file with valid URLs. You can refer to the options suggested in this issue [here](https://github.com/vumaasha/Atlas/issues/2#issuecomment-558268332)

**Comment by Bouncer51** [comment]
Could i get any csv file as mentioned in data collection to run the crawlers?

it is fine if some of links are broken, i am looking for product description data too, current data has images and product titles..but not description. if anything is available please help me out.

Thanks
